#include <songs.h>

const song_t FourSeasons RODATA_ATTR = {
    .notes = {
        {.note = E_5, .timeMs = 286},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 143},
        {.note = E_5, .timeMs = 143},
        {.note = B_5, .timeMs = 857},
        {.note = SILENCE, .timeMs = 71},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 143},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 143},
        {.note = E_5, .timeMs = 143},
        {.note = B_5, .timeMs = 857},
        {.note = SILENCE, .timeMs = 71},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 143},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = A_5, .timeMs = 143},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 286},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 286},
        {.note = D_SHARP_5, .timeMs = 286},
        {.note = B_4, .timeMs = 429},
        {.note = E_5, .timeMs = 286},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 143},
        {.note = E_5, .timeMs = 143},
        {.note = B_5, .timeMs = 857},
        {.note = SILENCE, .timeMs = 71},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 143},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 143},
        {.note = E_5, .timeMs = 143},
        {.note = B_5, .timeMs = 857},
        {.note = SILENCE, .timeMs = 71},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 143},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = A_5, .timeMs = 143},
        {.note = B_5, .timeMs = 143},
        {.note = A_5, .timeMs = 286},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = G_SHARP_5, .timeMs = 71},
        {.note = SILENCE, .timeMs = 71},
        {.note = F_SHARP_5, .timeMs = 286},
        {.note = D_SHARP_5, .timeMs = 286},
        {.note = B_4, .timeMs = 429},
    },
    .numNotes = 102,
    .shouldLoop = false
};

const song_t MetalGear RODATA_ATTR = {
    .notes = {
        {.note = E_5, .timeMs = 480},
        {.note = D_5, .timeMs = 480},
        {.note = C_5, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = D_5, .timeMs = 240},
        {.note = E_5, .timeMs = 240},
        {.note = A_4, .timeMs = 240},
        {.note = E_5, .timeMs = 480},
        {.note = D_5, .timeMs = 960},
        {.note = C_5, .timeMs = 240},
        {.note = D_5, .timeMs = 240},
        {.note = E_5, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = A_5, .timeMs = 240},
        {.note = G_5, .timeMs = 240},
        {.note = E_5, .timeMs = 240},
        {.note = C_5, .timeMs = 480},
        {.note = D_5, .timeMs = 960},
        {.note = E_5, .timeMs = 240},
        {.note = A_5, .timeMs = 240},
        {.note = C_6, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = B_5, .timeMs = 240},
        {.note = C_6, .timeMs = 240},
        {.note = D_6, .timeMs = 240},
        {.note = C_6, .timeMs = 480},
        {.note = A_5, .timeMs = 960},
        {.note = G_5, .timeMs = 240},
        {.note = A_5, .timeMs = 240},
        {.note = B_5, .timeMs = 480},
        {.note = SILENCE, .timeMs = 240},
        {.note = C_6, .timeMs = 240},
        {.note = B_5, .timeMs = 480},
        {.note = A_5, .timeMs = 240},
        {.note = G_5, .timeMs = 240},
        {.note = A_5, .timeMs = 1920},
        {.note = SILENCE, .timeMs = 480},
        {.note = SILENCE, .timeMs = 480},
        {.note = B_5, .timeMs = 480},
        {.note = A_5, .timeMs = 480},
        {.note = G_5, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = A_5, .timeMs = 240},
        {.note = B_5, .timeMs = 240},
        {.note = E_5, .timeMs = 240},
        {.note = B_5, .timeMs = 480},
        {.note = A_5, .timeMs = 960},
        {.note = G_5, .timeMs = 240},
        {.note = A_5, .timeMs = 240},
        {.note = B_5, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = E_6, .timeMs = 240},
        {.note = D_6, .timeMs = 240},
        {.note = B_5, .timeMs = 240},
        {.note = G_5, .timeMs = 480},
        {.note = A_5, .timeMs = 960},
        {.note = B_5, .timeMs = 240},
        {.note = E_6, .timeMs = 240},
        {.note = G_6, .timeMs = 960},
        {.note = SILENCE, .timeMs = 240},
        {.note = F_SHARP_6, .timeMs = 240},
        {.note = G_6, .timeMs = 240},
        {.note = A_6, .timeMs = 240},
        {.note = G_6, .timeMs = 480},
        {.note = E_6, .timeMs = 960},
        {.note = D_6, .timeMs = 240},
        {.note = E_6, .timeMs = 240},
        {.note = F_SHARP_6, .timeMs = 480},
        {.note = SILENCE, .timeMs = 240},
        {.note = G_6, .timeMs = 240},
        {.note = F_SHARP_6, .timeMs = 480},
        {.note = E_6, .timeMs = 240},
        {.note = D_6, .timeMs = 240},
        {.note = E_6, .timeMs = 1920},
        {.note = SILENCE, .timeMs = 480},
        {.note = SILENCE, .timeMs = 480},
    },
    .numNotes = 76,
    .shouldLoop = false
};

const song_t * allSongs[] = {
	&FourSeasons,
	&MetalGear,
};

const song_t* ICACHE_FLASH_ATTR getRandSong(void)
{
    return allSongs[(os_random() % (sizeof(allSongs) / sizeof(allSongs[0])))];
}
